@approot = http://localhost:5555

GET {{approot}}/api/welcome HTTP/1.1
# [HttpGet("/api/welcome")]
# public IActionResult Welcome()
###

GET {{approot}}/api/home/getdata1/111
# [HttpGet("[action]/{id:int}")]
# public IActionResult GetData1(int id)
###

GET {{approot}}/api/home/getdata2/222
# [HttpGet("[action]/{id:int}")]    
#  public IActionResult GetData2([FromRoute(Name = "id")] int UserId)
###

GET {{approot}}/api/home/getdata3/?id=333
# [HttpGet("[action]")]
# public IActionResult GetData3([FromQuery(Name = "id")] int UserId)
###

POST {{approot}}/api/home/post1
# [HttpPost("[action]")] 
# public IActionResult Post1()
###

POST {{approot}}/api/home/post2/222
# [HttpPost("[action]/{id:int}")]     
# public IActionResult Post2(int id)
###

POST {{approot}}/api/home/post3/333
# [HttpPost("[action]/{id:int}")]
# public IActionResult Post3([FromRoute(Name = "id")] int UserId)
###

POST {{approot}}/api/home/post4
content-type: application/json

{
    "userId": 1,
    "userName": "Emre"
}

# [HttpPost("[action]")]
# public IActionResult Post4(UserDto user) 
# json data key names are NOT case-sensitive
###

GET {{approot}}/api/token/create HTTP/1.1
###

GET {{approot}}/api/admin HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZ2l2ZW5fbmFtZSI6IkVtcmUiLCJuYmYiOjE3MTk3Mzc0MzUsImV4cCI6MTcyMDM0MjIzNSwiaWF0IjoxNzE5NzM3NDM1LCJpc3MiOiJOZXRBbmQiLCJhdWQiOiIqIn0.xhGCwYKrl9HshgQImL7YqJ7Mj3yuLpGS1iFoNh6K1w7oC97nvhWgljGXutuxBSD4SFxMJyYZIl-Q47F2jOxvDg
###



authorization: Basic someuser somekey
content-type: application/x-www-form-urlencoded