@approot = http://localhost:5555

GET {{approot}}/api/token/create HTTP/1.1
###

GET {{approot}}/api/token/createencrypted HTTP/1.1
###

POST {{approot}}/api/token/validate
// [HttpPost("[action]")]
// public IActionResult Validate([FromForm]string Token)
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMjM0NSIsImdpdmVuX25hbWUiOiJlbXJlLW11bWN1IiwibmJmIjoxNzIwMTgxNTM1LCJleHAiOjE3MjAxODI3MzUsImlhdCI6MTcyMDE4MTUzNSwiaXNzIjoiZW1yZS1tdW1jdSIsImF1ZCI6IioifQ.XbjnxE3Up3YIh5nGhj3Fk_F-459SvYbF1MemAvlSewmIgY1Qx2P25CQo4YtkQiGNmMyo6CT99B3Wbhq66nuNhQ
###

POST {{approot}}/api/token/validateencrypted
// [HttpPost("[action]")]
// public IActionResult ValidateEncrypted([FromForm]string Token)
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIiwiY3R5IjoiSldUIn0.PR8mTHXsZYSQ6gulsvB1cLTYsaCTn2vRdjYKab_jaWq-vs-B0VCYog.lcnCemEmYIZoc74A4Jerag.x4zfRyIq_PvF7xz53p_PliLMfedZj5gtkVN5PGzFM-rftEW-Sq0SoMEeKOLw7YoHY_LabNUs-cSwp8SG_KeQWLTxljpRWew3bAMFbNfuwzY4o9xemlynZqWjltZaYGBJP9jUIM5gj-v93pcsmqXNopST3doZKbP2zSewmIRg6YZYNgjFK2Gi1niGdRjcI1gzhe3caCVWKCYn6_3HxeKnnNZ135y6uYlBlsG2UMsl4HUwgOnyZN9qrxcvJ6RK96n5bzRdl_cpLK6W_ppEIeOlM-JB0LwjCCDwL69iBN6FoUhvc29ZyhjQbADpO2ACiORr_ToER8fs9jLGY2vcg-O5q9p8Yy0ysoVZ1jmMyNsJs_-0wNg7BJjRppkdFwgXuZ5Q2i36nkrPQl0vSLoHFM36MQ.gBh_STbpsZ_S16JG7Ki9RQ
###